//! Raw FFI declarations for the Hyprland Plugin API.
//!
//! # ABI Warning
//!
//! The Hyprland plugin API uses `extern "C"` linkage but passes **C++ objects**
//! (`std::string`, `std::function<>`, `std::any`, `std::shared_ptr<>`) across
//! the boundary. This means:
//!
//! - There is **no stable C ABI**. Plugins must be compiled with the same
//!   compiler and C++ standard library as the running Hyprland instance.
//! - Calling these functions directly from Rust requires a **C++ bridge shim**
//!   that converts between C-compatible types and C++ types.
//! - The raw function pointers declared here use opaque `*mut c_void` for
//!   C++ objects. A companion C++ translation unit (`bridge.cpp`) provides
//!   the actual symbol implementations.
//!
//! # Bridge
//!
//! Enable the `plugin-ffi` feature to compile the C++ bridge. This requires
//! Hyprland development headers (`pkg-config hyprland`).
//!
//! Without the feature, the symbols remain unresolved — the types and safe
//! wrappers are still usable for documentation and type definitions.

use std::ffi::c_void;
use std::os::raw::c_char;

/// Opaque handle type (`HANDLE = void*` in C++).
pub type Handle = *mut c_void;

/// Opaque pointer to a C++ `std::shared_ptr<HOOK_CALLBACK_FN>`.
pub type HookCallbackPtr = *mut c_void;

/// Opaque pointer to a C++ `CFunctionHook`.
pub type FunctionHookPtr = *mut c_void;

/// Opaque pointer to a C++ `std::shared_ptr<SHyprCtlCommand>`.
pub type HyprCtlCommandPtr = *mut c_void;

/// Opaque pointer to a C++ `Hyprlang::CConfigValue`.
pub type ConfigValuePtr = *mut c_void;

/// Opaque pointer to a C++ `IHyprLayout` (bridge wrapper).
pub type LayoutPtr = *mut c_void;

/// Opaque pointer to a C++ `IHyprWindowDecoration` (bridge wrapper).
pub type WindowDecorationPtr = *mut c_void;

/// Opaque pointer to a C++ `PHLWINDOW` (`shared_ptr<CWindow>`).
pub type WindowPtr = *mut c_void;

// ── Plugin lifecycle functions ───────────────────────────────────────
//
// These are the functions a plugin .so must EXPORT. Hyprland loads the
// plugin via dlopen and resolves these symbols.
//
// In Rust, these are generated by the `hyprland_plugin!` macro in
// the `lifecycle` module. They are documented here for reference.
//
// extern "C" {
//     fn pluginAPIVersion() -> std::string;    // must return "0.1"
//     fn pluginInit(handle: Handle) -> PLUGIN_DESCRIPTION_INFO;
//     fn pluginExit();
// }

// ── Layout vtable ───────────────────────────────────────────────────
//
// Passed to the bridge so that the C++ `RustLayoutBridge` (inherits
// `IHyprLayout`) can delegate virtual method calls to Rust trampolines.

/// Function pointer table for `Layout` trait methods.
///
/// Each field corresponds to one virtual method of `IHyprLayout`.
/// The `rust_layout` parameter in every callback is the `*mut LayoutData`
/// leaked by `register_layout`.
#[repr(C)]
pub struct LayoutVtable {
    pub on_enable: unsafe extern "C" fn(rust_layout: *mut c_void),
    pub on_disable: unsafe extern "C" fn(rust_layout: *mut c_void),
    pub get_layout_name: unsafe extern "C" fn(
        rust_layout: *mut c_void,
        out_ptr: *mut *const c_char,
        out_len: *mut usize,
    ),
    pub on_window_created_tiling:
        unsafe extern "C" fn(rust_layout: *mut c_void, window: *mut c_void, direction: i8),
    pub on_window_removed_tiling:
        unsafe extern "C" fn(rust_layout: *mut c_void, window: *mut c_void),
    pub is_window_tiled:
        unsafe extern "C" fn(rust_layout: *mut c_void, window: *mut c_void) -> bool,
    pub recalculate_monitor: unsafe extern "C" fn(rust_layout: *mut c_void, monitor_id: i64),
    pub recalculate_window: unsafe extern "C" fn(rust_layout: *mut c_void, window: *mut c_void),
    pub resize_active_window: unsafe extern "C" fn(
        rust_layout: *mut c_void,
        dx: f64,
        dy: f64,
        corner: u8,
        window: *mut c_void,
    ),
    pub fullscreen_request: unsafe extern "C" fn(
        rust_layout: *mut c_void,
        window: *mut c_void,
        current_mode: i8,
        effective_mode: i8,
    ),
    /// Returns `true` if the Rust side produced a response string.
    pub layout_message: unsafe extern "C" fn(
        rust_layout: *mut c_void,
        window: *mut c_void,
        msg_ptr: *const c_char,
        msg_len: usize,
        out_ptr: *mut *mut c_char,
        out_len: *mut usize,
    ) -> bool,
    pub switch_windows:
        unsafe extern "C" fn(rust_layout: *mut c_void, a: *mut c_void, b: *mut c_void),
    pub move_window_to: unsafe extern "C" fn(
        rust_layout: *mut c_void,
        window: *mut c_void,
        dir_ptr: *const c_char,
        dir_len: usize,
        silent: bool,
    ),
    pub alter_split_ratio: unsafe extern "C" fn(
        rust_layout: *mut c_void,
        window: *mut c_void,
        ratio: f32,
        exact: bool,
    ),
    pub replace_window_data:
        unsafe extern "C" fn(rust_layout: *mut c_void, from: *mut c_void, to: *mut c_void),
    pub predict_size_for_new_window_tiled:
        unsafe extern "C" fn(rust_layout: *mut c_void, out_x: *mut f64, out_y: *mut f64),
    /// Called when the C++ bridge destructor runs (unregistration or plugin unload).
    pub drop: unsafe extern "C" fn(rust_layout: *mut c_void),
}

// ── Decoration vtable ───────────────────────────────────────────────
//
// Passed to the bridge so that the C++ `RustDecorationBridge` (inherits
// `IHyprWindowDecoration`) can delegate virtual method calls to Rust.

/// Function pointer table for `WindowDecoration` trait methods.
#[repr(C)]
pub struct DecorationVtable {
    pub get_positioning_info: unsafe extern "C" fn(
        rust_deco: *mut c_void,
        out_policy: *mut u8,
        out_edges: *mut u8,
        out_priority: *mut u32,
        out_reserved: *mut bool,
    ),
    pub on_positioning_reply: unsafe extern "C" fn(rust_deco: *mut c_void, ephemeral: bool),
    pub draw: unsafe extern "C" fn(rust_deco: *mut c_void, monitor: *mut c_void, alpha: f32),
    pub get_decoration_type: unsafe extern "C" fn(rust_deco: *mut c_void) -> i8,
    pub update_window: unsafe extern "C" fn(rust_deco: *mut c_void, window: *mut c_void),
    pub damage_entire: unsafe extern "C" fn(rust_deco: *mut c_void),
    pub on_input:
        unsafe extern "C" fn(rust_deco: *mut c_void, input_type: u8, x: f64, y: f64) -> bool,
    pub get_decoration_layer: unsafe extern "C" fn(rust_deco: *mut c_void) -> u8,
    pub get_decoration_flags: unsafe extern "C" fn(rust_deco: *mut c_void) -> u64,
    pub get_display_name: unsafe extern "C" fn(
        rust_deco: *mut c_void,
        out_ptr: *mut *const c_char,
        out_len: *mut usize,
    ),
    /// Called when the C++ bridge destructor runs.
    pub drop: unsafe extern "C" fn(rust_deco: *mut c_void),
}

// ── HyprlandAPI bridge functions ─────────────────────────────────────
//
// These `extern "C"` functions are provided by `bridge.cpp`. Each one:
// 1. Converts C-compatible parameters to C++ types
// 2. Calls the real HyprlandAPI:: function
// 3. Converts the C++ result back to C-compatible output parameters
//
// The bridge.cpp is compiled via build.rs when the `plugin-ffi` feature
// is enabled. Without it, these symbols are unresolved.

unsafe extern "C" {
    // ── Config ───────────────────────────────────────────────────────

    /// Add a config value. Must be called during `pluginInit` only.
    ///
    /// C++ signature:
    /// `bool addConfigValue(HANDLE, const std::string&, const Hyprlang::CConfigValue&)`
    ///
    /// The value is passed as decomposed components:
    /// - `value_type`: 0=Int(bool), 1=Int, 2=Float, 3=String, 4=Color(u32), 5=Vec2
    /// - `int_val`: for Int/Bool/Color types
    /// - `float_val`/`float_val2`: for Float/Vec2 types
    /// - `str_ptr`/`str_len`: for String type
    #[link_name = "hyprland_api_add_config_value"]
    pub fn add_config_value(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        value_type: u8,
        int_val: i64,
        float_val: f64,
        float_val2: f64,
        str_ptr: *const c_char,
        str_len: usize,
    ) -> bool;

    /// Get a config value pointer (valid for plugin lifetime).
    ///
    /// C++ signature:
    /// `Hyprlang::CConfigValue* getConfigValue(HANDLE, const std::string&)`
    #[link_name = "hyprland_api_get_config_value"]
    pub fn get_config_value(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
    ) -> ConfigValuePtr;

    /// Register a config keyword handler. Must be called during `pluginInit` only.
    ///
    /// C++ signature:
    /// `bool addConfigKeyword(HANDLE, const std::string&, PCONFIGHANDLERFUNC, SHandlerOptions)`
    ///
    /// Callback signature: `fn(user_data, value_ptr, value_len) -> bool`
    #[link_name = "hyprland_api_add_config_keyword"]
    pub fn add_config_keyword(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        callback: Option<unsafe extern "C" fn(*mut c_void, *const c_char, usize) -> bool>,
        user_data: *mut c_void,
        allow_flags: bool,
        allow_default: bool,
    ) -> bool;

    // ── Hooks ────────────────────────────────────────────────────────

    /// Register a callback for a hook event.
    ///
    /// C++ signature:
    /// `SP<HOOK_CALLBACK_FN> registerCallbackDynamic(HANDLE, const std::string&, HOOK_CALLBACK_FN)`
    ///
    /// Callback signature: `fn(user_data, callback_info, event_data)`
    /// - `callback_info`: pointer to SCallbackInfo (has `cancelled` bool)
    /// - `event_data`: pointer to event-specific data (via std::any)
    #[link_name = "hyprland_api_register_callback"]
    pub fn register_callback(
        handle: Handle,
        event_ptr: *const c_char,
        event_len: usize,
        callback: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, *mut c_void)>,
        user_data: *mut c_void,
    ) -> HookCallbackPtr;

    /// Unregister a callback (drops the shared_ptr).
    #[link_name = "hyprland_api_unregister_callback"]
    pub fn unregister_callback(handle: Handle, callback: HookCallbackPtr) -> bool;

    // ── HyprCtl ──────────────────────────────────────────────────────

    /// Execute a hyprctl command synchronously.
    ///
    /// C++ signature:
    /// `std::string invokeHyprctlCommand(const std::string&, const std::string&, const std::string&)`
    ///
    /// Result string written to out_ptr/out_len. Caller must free via
    /// `free_bridge_string`.
    #[link_name = "hyprland_api_invoke_hyprctl"]
    pub fn invoke_hyprctl(
        call_ptr: *const c_char,
        call_len: usize,
        args_ptr: *const c_char,
        args_len: usize,
        format_ptr: *const c_char,
        format_len: usize,
        out_ptr: *mut *mut c_char,
        out_len: *mut usize,
    ) -> bool;

    /// Register a custom hyprctl command.
    ///
    /// C++ signature:
    /// `SP<SHyprCtlCommand> registerHyprCtlCommand(HANDLE, SHyprCtlCommand)`
    ///
    /// Callback signature: `fn(user_data, format, args_ptr, args_len, out_ptr, out_len)`
    /// Caller must free out_ptr via `free_bridge_string`.
    #[link_name = "hyprland_api_register_hyprctl_command"]
    pub fn register_hyprctl_command(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        exact: bool,
        callback: Option<
            unsafe extern "C" fn(
                *mut c_void,
                u8,
                *const c_char,
                usize,
                *mut *mut c_char,
                *mut usize,
            ),
        >,
        user_data: *mut c_void,
    ) -> HyprCtlCommandPtr;

    /// Unregister a custom hyprctl command.
    #[link_name = "hyprland_api_unregister_hyprctl_command"]
    pub fn unregister_hyprctl_command(handle: Handle, cmd: HyprCtlCommandPtr) -> bool;

    // ── Dispatchers ──────────────────────────────────────────────────

    /// Register a custom keybind dispatcher (V2 API).
    ///
    /// C++ signature:
    /// `bool addDispatcherV2(HANDLE, const std::string&, std::function<SDispatchResult(std::string)>)`
    ///
    /// Callback signature: `fn(user_data, args_ptr, args_len, out_pass, out_success, out_error_ptr, out_error_len)`
    #[link_name = "hyprland_api_add_dispatcher"]
    pub fn add_dispatcher(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        callback: Option<
            unsafe extern "C" fn(
                *mut c_void,
                *const c_char,
                usize,
                *mut bool,
                *mut bool,
                *mut *mut c_char,
                *mut usize,
            ),
        >,
        user_data: *mut c_void,
    ) -> bool;

    /// Remove a custom dispatcher.
    #[link_name = "hyprland_api_remove_dispatcher"]
    pub fn remove_dispatcher(handle: Handle, name_ptr: *const c_char, name_len: usize) -> bool;

    // ── Layout ───────────────────────────────────────────────────────

    /// Register a custom window layout.
    ///
    /// C++ signature:
    /// `bool addLayout(HANDLE, const std::string&, IHyprLayout*)`
    ///
    /// The bridge creates a C++ `RustLayoutBridge` (inherits `IHyprLayout`)
    /// that stores `rust_layout` and `vtable`, delegating virtual calls to
    /// Rust trampolines.
    ///
    /// Returns a pointer to the bridge object (`IHyprLayout*`) on success,
    /// or null on failure.
    #[link_name = "hyprland_api_add_layout"]
    pub fn add_layout(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        rust_layout: *mut c_void,
        vtable: *const LayoutVtable,
    ) -> LayoutPtr;

    /// Remove a custom layout and destroy the C++ bridge wrapper.
    ///
    /// The bridge destructor calls `vtable.drop(rust_layout)` to clean up
    /// the Rust side.
    #[link_name = "hyprland_api_remove_layout"]
    pub fn remove_layout(handle: Handle, layout: LayoutPtr) -> bool;

    // ── Window Decoration ────────────────────────────────────────────

    /// Add a window decoration.
    ///
    /// C++ signature:
    /// `bool addWindowDecoration(HANDLE, PHLWINDOW, UP<IHyprWindowDecoration>)`
    ///
    /// `window_handle` must be a heap-allocated `PHLWINDOW*` obtained via
    /// [`clone_window_handle`].
    ///
    /// Returns a pointer to the bridge object on success, or null on failure.
    #[link_name = "hyprland_api_add_window_decoration"]
    pub fn add_window_decoration(
        handle: Handle,
        window_handle: *mut c_void,
        rust_deco: *mut c_void,
        vtable: *const DecorationVtable,
    ) -> WindowDecorationPtr;

    /// Remove a window decoration. The C++ bridge destructor calls
    /// `vtable.drop(rust_deco)`.
    #[link_name = "hyprland_api_remove_window_decoration"]
    pub fn remove_window_decoration(handle: Handle, decoration: WindowDecorationPtr) -> bool;

    // ── Window Handle Helpers ────────────────────────────────────────

    /// Extract a `PHLWINDOW` from a `std::any*` (hook callback data) and
    /// heap-allocate a copy. Returns null if extraction fails.
    ///
    /// The caller must free the returned handle via [`release_window_handle`].
    #[link_name = "hyprland_api_clone_window_handle"]
    pub fn clone_window_handle(any_ptr: *mut c_void) -> *mut c_void;

    /// Free a heap-allocated `PHLWINDOW` obtained via [`clone_window_handle`].
    #[link_name = "hyprland_api_release_window_handle"]
    pub fn release_window_handle(handle: *mut c_void);

    // ── Notifications ────────────────────────────────────────────────

    /// Show a notification.
    ///
    /// C++ signature:
    /// `bool addNotification(HANDLE, const std::string&, const CHyprColor&, float)`
    #[link_name = "hyprland_api_add_notification"]
    pub fn add_notification(
        handle: Handle,
        text_ptr: *const c_char,
        text_len: usize,
        r: f64,
        g: f64,
        b: f64,
        a: f64,
        time_ms: f32,
    ) -> bool;

    /// Show a notification (v2, with icon).
    ///
    /// C++ signature:
    /// `bool addNotificationV2(HANDLE, const std::unordered_map<std::string, std::any>&)`
    #[link_name = "hyprland_api_add_notification_v2"]
    pub fn add_notification_v2(
        handle: Handle,
        text_ptr: *const c_char,
        text_len: usize,
        time_ms: u64,
        r: f64,
        g: f64,
        b: f64,
        a: f64,
        icon: u8,
    ) -> bool;

    // ── Config Reload ────────────────────────────────────────────────

    /// Queue a config reload (asynchronous).
    #[link_name = "hyprland_api_reload_config"]
    pub fn reload_config() -> bool;

    // ── Function Hooking (Advanced/Unstable) ─────────────────────────

    /// Create a trampoline function hook to an internal Hyprland function.
    ///
    /// **WARNING**: No API stability guaranteed.
    #[link_name = "hyprland_api_create_function_hook"]
    pub fn create_function_hook(
        handle: Handle,
        source: *const c_void,
        destination: *const c_void,
    ) -> FunctionHookPtr;

    /// Remove and unhook a function hook.
    #[link_name = "hyprland_api_remove_function_hook"]
    pub fn remove_function_hook(handle: Handle, hook: FunctionHookPtr) -> bool;

    /// Find functions by demangled name. Returns count; fills addresses array.
    ///
    /// C++ signature:
    /// `std::vector<SFunctionMatch> findFunctionsByName(HANDLE, const std::string&)`
    ///
    /// Caller must free out_addresses via `free_bridge_array`.
    #[link_name = "hyprland_api_find_functions_by_name"]
    pub fn find_functions_by_name(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        out_addresses: *mut *const c_void,
        out_count: *mut usize,
    ) -> bool;

    // ── Version ──────────────────────────────────────────────────────

    /// Get the server's ABI hash string (static, no free needed).
    #[link_name = "__hyprland_api_get_hash"]
    pub fn get_server_hash() -> *const c_char;

    /// Get Hyprland version info.
    ///
    /// String pointers are valid until the next call (static buffers in bridge).
    #[link_name = "hyprland_api_get_version"]
    pub fn get_version(
        handle: Handle,
        out_hash: *mut *const c_char,
        out_hash_len: *mut usize,
        out_tag: *mut *const c_char,
        out_tag_len: *mut usize,
        out_dirty: *mut bool,
        out_branch: *mut *const c_char,
        out_branch_len: *mut usize,
    ) -> bool;

    // ── Memory management ────────────────────────────────────────────

    /// Free a string allocated by the bridge (malloc'd).
    #[link_name = "hyprland_api_free_string"]
    pub fn free_bridge_string(ptr: *mut c_char);

    /// Free an array allocated by the bridge (malloc'd).
    #[link_name = "hyprland_api_free_array"]
    pub fn free_bridge_array(ptr: *mut c_void);
}
