//! Raw FFI declarations for the Hyprland Plugin API.
//!
//! # ABI Warning
//!
//! The Hyprland plugin API uses `extern "C"` linkage but passes **C++ objects**
//! (`std::string`, `std::function<>`, `std::any`, `std::shared_ptr<>`) across
//! the boundary. This means:
//!
//! - There is **no stable C ABI**. Plugins must be compiled with the same
//!   compiler and C++ standard library as the running Hyprland instance.
//! - Calling these functions directly from Rust requires a **C++ bridge shim**
//!   that converts between C-compatible types and C++ types.
//! - The raw function pointers declared here use opaque `*mut c_void` for
//!   C++ objects. A companion C++ translation unit is needed to provide the
//!   actual symbol implementations that Rust can call.
//!
//! # Usage
//!
//! These declarations are provided for:
//! - Documentation of the complete API surface
//! - Use with a C++ bridge (e.g. `cxx` crate or manual shim)
//! - Direct FFI by advanced users who understand the ABI constraints
//!
//! For most users, the safe wrappers in the parent `plugin` module are
//! preferred once a C++ bridge is established.

use std::ffi::c_void;
use std::os::raw::c_char;

/// Opaque handle type (`HANDLE = void*` in C++).
pub type Handle = *mut c_void;

/// Opaque pointer to a C++ `std::shared_ptr<HOOK_CALLBACK_FN>`.
pub type HookCallbackPtr = *mut c_void;

/// Opaque pointer to a C++ `CFunctionHook`.
pub type FunctionHookPtr = *mut c_void;

/// Opaque pointer to a C++ `std::shared_ptr<SHyprCtlCommand>`.
pub type HyprCtlCommandPtr = *mut c_void;

/// Opaque pointer to a C++ `Hyprlang::CConfigValue`.
pub type ConfigValuePtr = *mut c_void;

/// Opaque pointer to a C++ `IHyprLayout`.
pub type LayoutPtr = *mut c_void;

/// Opaque pointer to a C++ `IHyprWindowDecoration`.
pub type WindowDecorationPtr = *mut c_void;

/// Opaque pointer to a C++ `PHLWINDOW` (`shared_ptr<CWindow>`).
pub type WindowPtr = *mut c_void;

// ── Plugin lifecycle functions ───────────────────────────────────────
//
// These are the functions a plugin .so must EXPORT. Hyprland loads the
// plugin via dlopen and resolves these symbols.
//
// In Rust, these would be generated by the `hyprland_plugin!` macro in
// the `lifecycle` module. They are documented here for reference.
//
// extern "C" {
//     fn pluginAPIVersion() -> std::string;    // must return "0.1"
//     fn pluginInit(handle: Handle) -> PLUGIN_DESCRIPTION_INFO;
//     fn pluginExit();
// }

// ── HyprlandAPI namespace functions ──────────────────────────────────
//
// NOTE: These functions are defined in Hyprland's address space. When a
// plugin .so is loaded, it can call them because it's in the same process.
// However, the actual symbols use C++ name mangling within the
// `HyprlandAPI` namespace, and pass C++ types.
//
// The declarations below use C-compatible approximations. A real
// implementation needs a C++ bridge that:
// 1. Exports C-linkage wrapper functions
// 2. Converts between C types and C++ types
// 3. Calls the actual HyprlandAPI:: functions

unsafe extern "C" {
    // ── Config ───────────────────────────────────────────────────────

    /// Add a config value. Must be called during `pluginInit` only.
    /// Config values must be in the `plugin:` namespace.
    ///
    /// C++ signature:
    /// `bool addConfigValue(HANDLE, const std::string&, const Hyprlang::CConfigValue&)`
    ///
    /// Bridge: name_ptr/name_len → std::string, value_ptr → CConfigValue*
    #[link_name = "hyprland_api_add_config_value"]
    pub fn add_config_value(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        value_ptr: ConfigValuePtr,
    ) -> bool;

    /// Get a config value pointer (valid for plugin lifetime).
    ///
    /// C++ signature:
    /// `Hyprlang::CConfigValue* getConfigValue(HANDLE, const std::string&)`
    #[link_name = "hyprland_api_get_config_value"]
    pub fn get_config_value(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
    ) -> ConfigValuePtr;

    // ── Hooks ────────────────────────────────────────────────────────

    /// Register a callback for a hook event.
    /// Returns an opaque pointer — dropping/freeing it unregisters the callback.
    ///
    /// C++ signature:
    /// `SP<HOOK_CALLBACK_FN> registerCallbackDynamic(HANDLE, const std::string&, HOOK_CALLBACK_FN)`
    ///
    /// Bridge: event name as C string, callback as extern "C" fn pointer
    #[link_name = "hyprland_api_register_callback"]
    pub fn register_callback(
        handle: Handle,
        event_ptr: *const c_char,
        event_len: usize,
        callback: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, *mut c_void)>,
        user_data: *mut c_void,
    ) -> HookCallbackPtr;

    /// Unregister a callback (deprecated — just drop the pointer).
    #[link_name = "hyprland_api_unregister_callback"]
    pub fn unregister_callback(handle: Handle, callback: HookCallbackPtr) -> bool;

    // ── HyprCtl ──────────────────────────────────────────────────────

    /// Execute a hyprctl command synchronously.
    ///
    /// C++ signature:
    /// `std::string invokeHyprctlCommand(const std::string&, const std::string&, const std::string&)`
    ///
    /// Bridge: returns result via out_ptr/out_len
    #[link_name = "hyprland_api_invoke_hyprctl"]
    pub fn invoke_hyprctl(
        call_ptr: *const c_char,
        call_len: usize,
        args_ptr: *const c_char,
        args_len: usize,
        format_ptr: *const c_char,
        format_len: usize,
        out_ptr: *mut *mut c_char,
        out_len: *mut usize,
    ) -> bool;

    /// Register a custom hyprctl command.
    ///
    /// C++ signature:
    /// `SP<SHyprCtlCommand> registerHyprCtlCommand(HANDLE, SHyprCtlCommand)`
    #[link_name = "hyprland_api_register_hyprctl_command"]
    pub fn register_hyprctl_command(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        exact: bool,
        callback: Option<
            unsafe extern "C" fn(u8, *const c_char, usize, *mut *mut c_char, *mut usize),
        >,
    ) -> HyprCtlCommandPtr;

    /// Unregister a custom hyprctl command.
    #[link_name = "hyprland_api_unregister_hyprctl_command"]
    pub fn unregister_hyprctl_command(handle: Handle, cmd: HyprCtlCommandPtr) -> bool;

    // ── Dispatchers ──────────────────────────────────────────────────

    /// Register a custom keybind dispatcher.
    ///
    /// C++ signature:
    /// `bool addDispatcherV2(HANDLE, const std::string&, std::function<SDispatchResult(std::string)>)`
    #[link_name = "hyprland_api_add_dispatcher"]
    pub fn add_dispatcher(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        callback: Option<
            unsafe extern "C" fn(
                *const c_char,
                usize,
                *mut bool,
                *mut bool,
                *mut *mut c_char,
                *mut usize,
            ),
        >,
    ) -> bool;

    /// Remove a custom dispatcher.
    #[link_name = "hyprland_api_remove_dispatcher"]
    pub fn remove_dispatcher(handle: Handle, name_ptr: *const c_char, name_len: usize) -> bool;

    // ── Layout ───────────────────────────────────────────────────────

    /// Register a custom window layout.
    ///
    /// C++ signature:
    /// `bool addLayout(HANDLE, const std::string&, IHyprLayout*)`
    #[link_name = "hyprland_api_add_layout"]
    pub fn add_layout(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        layout: LayoutPtr,
    ) -> bool;

    /// Remove a custom layout.
    #[link_name = "hyprland_api_remove_layout"]
    pub fn remove_layout(handle: Handle, layout: LayoutPtr) -> bool;

    // ── Window Decoration ────────────────────────────────────────────

    /// Add a window decoration.
    ///
    /// C++ signature:
    /// `bool addWindowDecoration(HANDLE, PHLWINDOW, UP<IHyprWindowDecoration>)`
    #[link_name = "hyprland_api_add_window_decoration"]
    pub fn add_window_decoration(
        handle: Handle,
        window: WindowPtr,
        decoration: WindowDecorationPtr,
    ) -> bool;

    /// Remove a window decoration.
    #[link_name = "hyprland_api_remove_window_decoration"]
    pub fn remove_window_decoration(handle: Handle, decoration: WindowDecorationPtr) -> bool;

    // ── Notifications ────────────────────────────────────────────────

    /// Show a notification.
    ///
    /// C++ signature:
    /// `bool addNotification(HANDLE, const std::string&, const CHyprColor&, float)`
    #[link_name = "hyprland_api_add_notification"]
    pub fn add_notification(
        handle: Handle,
        text_ptr: *const c_char,
        text_len: usize,
        r: f64,
        g: f64,
        b: f64,
        a: f64,
        time_ms: f32,
    ) -> bool;

    /// Show a notification (v2, with icon).
    #[link_name = "hyprland_api_add_notification_v2"]
    pub fn add_notification_v2(
        handle: Handle,
        text_ptr: *const c_char,
        text_len: usize,
        time_ms: u64,
        r: f64,
        g: f64,
        b: f64,
        a: f64,
        icon: u8,
    ) -> bool;

    // ── Config Reload ────────────────────────────────────────────────

    /// Queue a config reload (asynchronous).
    #[link_name = "hyprland_api_reload_config"]
    pub fn reload_config() -> bool;

    // ── Function Hooking (Advanced/Unstable) ─────────────────────────

    /// Create a trampoline function hook to an internal Hyprland function.
    ///
    /// **WARNING**: No API stability guaranteed. Internal functions may be
    /// removed, renamed, or changed between any Hyprland version.
    #[link_name = "hyprland_api_create_function_hook"]
    pub fn create_function_hook(
        handle: Handle,
        source: *const c_void,
        destination: *const c_void,
    ) -> FunctionHookPtr;

    /// Remove and unhook a function hook.
    #[link_name = "hyprland_api_remove_function_hook"]
    pub fn remove_function_hook(handle: Handle, hook: FunctionHookPtr) -> bool;

    /// Find functions by demangled name. Returns count; fills addresses array.
    ///
    /// C++ signature:
    /// `std::vector<SFunctionMatch> findFunctionsByName(HANDLE, const std::string&)`
    #[link_name = "hyprland_api_find_functions_by_name"]
    pub fn find_functions_by_name(
        handle: Handle,
        name_ptr: *const c_char,
        name_len: usize,
        out_addresses: *mut *const c_void,
        out_count: *mut usize,
    ) -> bool;

    // ── Version ──────────────────────────────────────────────────────

    /// Get the server's ABI hash string.
    #[link_name = "__hyprland_api_get_hash"]
    pub fn get_server_hash() -> *const c_char;

    /// Get Hyprland version info.
    ///
    /// C++ signature:
    /// `SVersionInfo getHyprlandVersion(HANDLE)`
    ///
    /// Bridge: fills out struct fields
    #[link_name = "hyprland_api_get_version"]
    pub fn get_version(
        handle: Handle,
        out_hash: *mut *const c_char,
        out_hash_len: *mut usize,
        out_tag: *mut *const c_char,
        out_tag_len: *mut usize,
        out_dirty: *mut bool,
        out_branch: *mut *const c_char,
        out_branch_len: *mut usize,
    ) -> bool;
}
