// Lifecycle bridge: expose Hyprland's C++ plugin entrypoints and delegate to
// Rust lifecycle shims generated by `hyprland_plugin!`.
#include "common.h"

#include <stdexcept>

extern "C" const char* hyprland_rs_plugin_api_version();
extern "C" bool hyprland_rs_plugin_init(void* handle);
extern "C" bool hyprland_rs_plugin_get_description(
    const char** out_name_ptr, size_t* out_name_len,
    const char** out_description_ptr, size_t* out_description_len,
    const char** out_author_ptr, size_t* out_author_len,
    const char** out_version_ptr, size_t* out_version_len
);
extern "C" bool hyprland_rs_plugin_get_error(const char** out_error_ptr, size_t* out_error_len);
extern "C" void hyprland_rs_plugin_exit();

extern "C" void hyprland_bridge_lifecycle_marker() {}

extern "C" std::string pluginAPIVersion() {
    const char* version = hyprland_rs_plugin_api_version();
    return version ? std::string(version) : std::string();
}

extern "C" PLUGIN_DESCRIPTION_INFO pluginInit(HANDLE handle) {
    const bool ok = hyprland_rs_plugin_init(handle);
    if (!ok) {
        const char* err_ptr = nullptr;
        size_t err_len = 0;
        if (hyprland_rs_plugin_get_error(&err_ptr, &err_len) && err_ptr && err_len > 0) {
            throw std::runtime_error(std::string(err_ptr, err_len));
        }
        throw std::runtime_error("Rust plugin initialization failed");
    }

    const char* name_ptr = nullptr;
    size_t name_len = 0;
    const char* description_ptr = nullptr;
    size_t description_len = 0;
    const char* author_ptr = nullptr;
    size_t author_len = 0;
    const char* version_ptr = nullptr;
    size_t version_len = 0;

    if (!hyprland_rs_plugin_get_description(
            &name_ptr, &name_len,
            &description_ptr, &description_len,
            &author_ptr, &author_len,
            &version_ptr, &version_len
        )) {
        throw std::runtime_error("Rust plugin did not provide a plugin description");
    }

    PLUGIN_DESCRIPTION_INFO info;
    if (name_ptr && name_len > 0)
        info.name = std::string(name_ptr, name_len);
    if (description_ptr && description_len > 0)
        info.description = std::string(description_ptr, description_len);
    if (author_ptr && author_len > 0)
        info.author = std::string(author_ptr, author_len);
    if (version_ptr && version_len > 0)
        info.version = std::string(version_ptr, version_len);
    return info;
}

extern "C" void pluginExit() {
    hyprland_rs_plugin_exit();
}
